# ref https://raw.githubusercontent.com/nais/naisd/master/nais_example.yaml
image: docker.adeo.no:5000/fo/modiaflatefs
team: oppfolging
replicas:
  min: 2
  max: 4
  cpuThresholdPercentage: 50
port: 8080
healthcheck:
  liveness:
    path: modiaflatefs/internal/isAlive
    initialDelay: 20
  readiness:
    path: modiaflatefs/internal/isReady
    initialDelay: 20
prometheus:
  enabled: true
  path: modiaflatefs/internal/metrics
resources:
  limits:
    cpu: 3
    memory: 1024Mi
  requests:
    cpu: 200m
    memory: 512Mi
fasitResources:
  used:
  - alias: loadbalancer:modiaflatefs
    resourceType: loadbalancerconfig
  - alias: srvmodiaflatefs
    resourceType: credential

  # security resources
  - alias: isso-rp-user
    resourceType: credential
  - alias: isso-host
    resourceType: baseUrl
  - alias: isso-jwks
    resourceType: baseUrl
  - alias: isso-issuer
    resourceType: baseUrl
  - alias: isso.isalive
    resourceType: baseUrl
  - alias: veilarblogin.redirect-url
    resourceType: restservice
    propertyMap:
      url: OIDC_REDIRECT_URL

alertProfiles:
  - common-java-modules
