apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: modiaflatefs
  namespace: personoversikt
  cluster: prod-fss
  labels:
    team: personoversikt
spec:
  image: {{image}}
  port: 8080
  webproxy: true
  team: personoversikt
  liveness:
    path: /modiaflatefs/internal/isAlive
    initialDelay: 20
  readiness:
    path: /modiaflatefs/internal/isReady
    initialDelay: 20
  prometheus:
    enabled: true
    path: /modiaflatefs/internal/metrics
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 2000m
      memory: 512Mi
  ingresses:
    - https://app.adeo.no/modiaflatefs
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 60
  azure:
    application:
      enabled: true
      tenant: nav.no
  env:
    - name: APP_NAME
      value: "modiaflatefs"
    - name: APP_VERSION
      value: "{{ version }}"
    - name: MILJO_SUFFIX
      value: ""
    - name: IDP_DISCOVERY_URL
      value: "https://isso.adeo.no/isso/oauth2/.well-known/openid-configuration"
    - name: IDP_CLIENT_ID
      value: "modialogin-p"
    - name: IDP_ISSUER
      value: "https://isso.adeo.no:443/isso/oauth2"
    - name: DELEGATED_LOGIN_URL
      value: "https://app.adeo.no/modialogin/api/start"
    - name: DELEGATED_REFRESH_URL
      value: "https://app.adeo.no/modialogin/api/refresh"
    - name: AUTH_TOKEN_RESOLVER
      value: "modia_ID_token"
    - name: REFRESH_TOKEN_RESOLVER
      value: "modia_refresh_token"
    - name: CSP_DIRECTIVES
      value: "default-src 'self';\
      script-src 'self' 'unsafe-inline';\
      font-src 'self' data:;\
      connect-src 'self' wss://veilederflatehendelser.adeo.no;\
      report-uri /frontendlogger/api/warn;"
