apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: modiaflatefs
  namespace: default
  cluster: prod-fss
  labels:
    team: personoversikt
spec:
  image: {{image}}
  port: 8080
  team: personoversikt
  liveness:
    path: /modiaflatefs/internal/isAlive
    initialDelay: 20
  readiness:
    path: /modiaflatefs/internal/isReady
    initialDelay: 20
  prometheus:
    enabled: true
    path: /modiaflatefs/internal/metrics
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: 3000m
      memory: 1024Mi
  ingresses:
    - https://app.adeo.no/modiaflatefs
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 60
  vault:
    enabled: true
    paths:
      - kvPath: /credential/data/prod/isso-rp-user
        mountPath: /var/run/secrets/nais.io/isso-rp-user
      - kvPath: /serviceuser/data/prod/srvmodiaflatefs
        mountPath: /var/run/secrets/nais.io/service_user
  env:
    - name: ISSO_HOST_URL
      value: "https://isso.adeo.no/isso/oauth2"
    - name: ISSO_ISALIVE_URL
      value: "https://isso.adeo.no/isso/isAlive.jsp"
    - name: ISSO_ISSUER_URL
      value: "https://isso.adeo.no:443/isso/oauth2"
    - name: ISSO_JWKS_URL
      value: "https://isso.adeo.no/isso/oauth2/connect/jwk_uri"
    - name: OIDC_REDIRECT_URL
      value: "https://app.adeo.no/veilarblogin/api/login"
    - name: VEILARBLOGIN_AAD_LOGIN_URL
      value: "https://app.adeo.no/veilarblogin/api/aad-login"
    - name: AAD_DISCOVERY_URL
      value: "https://login.microsoftonline.com/62366534-1ec3-4962-8869-9b5535279d0b/v2.0/.well-known/openid-configuration"
    - name: VEILARBLOGIN_AAD_CLIENT_ID
      value: "109c7064-47c9-4e34-b735-8cdc0d383cc1"
