---
apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  labels:
    team: personoversikt
  annotations:
    "nais.io/run-as-group": "0"
    "nais.io/read-only-file-system": "false"
  name: modiaflatefs-redis-{{q_env}}
  namespace: personoversikt
spec:
  image: bitnami/redis:7.0.5
  port: 6379
  replicas: # A single Redis-app doesn't scale
    min: 1
    max: 1 # More replicas doesn't sync
  resources: # you need to monitor the resource usage yourself
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  service:
    port: 6379
    protocol: redis
  envFrom:
    - secret: modiaflatefs-redis-{{q_env}}
---
apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  labels:
    team: personoversikt
  name: modiaflatefs-redis-redisexporter-{{q_env}}
  namespace: personoversikt
spec:
  image: oliver006/redis_exporter:v1.45.0-alpine
  port: 9121
  prometheus:
    enabled: true
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      cpu: 100m
      memory: 100Mi
    requests:
      cpu: 100m
      memory: 100Mi
  liveness:
    path: /health
  env:
    - name: REDIS_ADDR
      value: modiaflatefs-redis-{{q_env}}:6379
    - name: REDIS_EXPORTER_LOG_FORMAT
      value: json
  envFrom:
    - secret: modiaflatefs-redis-{{q_env}}
