apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: modiaflatefs
  namespace: {{ namespace }}
  cluster: dev-fss
  labels:
    team: personoversikt
spec:
  image: {{image}}
  port: 8080
  webproxy: true
  team: personoversikt
  liveness:
    path: /modiaflatefs/internal/isAlive
    initialDelay: 20
  readiness:
    path: /modiaflatefs/internal/isReady
    initialDelay: 20
  prometheus:
    enabled: true
    path: /modiaflatefs/internal/metrics
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: 3000m
      memory: 1024Mi
  ingresses:
    - https://app-{{ namespace }}.adeo.no/modiaflatefs
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 60
  vault:
    enabled: true
    paths:
      - kvPath: /credential/data/dev/isso-rp-user-{{ namespace }}
        mountPath: /var/run/secrets/nais.io/isso-rp-user
      - kvPath: /serviceuser/data/dev/srvmodiaflatefs
        mountPath: /var/run/secrets/nais.io/service_user
  env:
    - name: OPENAM_DISCOVERY_URL
      value: "https://isso-q.adeo.no/isso/oauth2/.well-known/openid-configuration"
    - name: VEILARBLOGIN_OPENAM_CLIENT_ID
      value: "veilarblogin-{{ namespace }}"
    - name: VEILARBLOGIN_OPENAM_LOGIN_URL
      value: "https://app-{{ namespace }}.adeo.no/veilarblogin/api/start"
    - name: AAD_DISCOVERY_URL
      value: "https://login.microsoftonline.com/966ac572-f5b7-4bbe-aa88-c76419c0f851/v2.0/.well-known/openid-configuration"
    - name: VEILARBLOGIN_AAD_CLIENT_ID
      value: "2edd96a2-fb5a-4dfa-8f36-848ae306f9b1"
    - name: VEILARBLOGIN_AAD_LOGIN_URL
      value: "https://app-{{ namespace }}.adeo.no/veilarblogin/api/aad-login"
    - name: UNLEASH_API_URL
      value: "https://unleash.nais.io/api/"
