apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: modiaflatefs
  namespace: {{ namespace }}
  cluster: dev-fss
  labels:
    team: personoversikt
spec:
  image: {{image}}
  port: 8080
  webproxy: true
  team: personoversikt
  liveness:
    path: /modiaflatefs/internal/isAlive
    initialDelay: 20
  readiness:
    path: /modiaflatefs/internal/isReady
    initialDelay: 20
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 192Mi
  ingresses:
    - https://app-{{ namespace }}.adeo.no/modiaflatefs
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 60
  env:
    - name: APP_NAME
      value: "modiaflatefs"
    - name: APP_VERSION
      value: "{{ version }}"
    - name: IDP_DISCOVERY_URL
      value: "https://isso-q.adeo.no/isso/oauth2/.well-known/openid-configuration"
    - name: IDP_CLIENT_ID
      value: "modialogin-{{ namespace }}"
    - name: DELEGATED_LOGIN_URL
      value: "https://app-{{ namespace }}.adeo.no/modialogin/api/start"
    - name: AUTH_TOKEN_RESOLVER
      value: "modia_ID_token"
    - name: CSP_DIRECTIVES
      value: "default-src 'self';\
      script-src 'self' 'unsafe-inline';\
      font-src 'self' data:;\
      connect-src 'self' wss://veilederflatehendelser-{{ namespace }}.adeo.no;\
      report-uri /frontendlogger/api/warn;"
