apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: modiaflatefs-{{ q_env }}
  namespace: personoversikt
  cluster: dev-fss
  labels:
    team: personoversikt
  annotations:
    nginx.ingress.kubernetes.io/proxy-buffer-size: "8k"
spec:
  image: {{image}}
  port: 8080
  webproxy: true
  team: personoversikt
  liveness:
    path: /modiaflatefs/internal/isAlive
    initialDelay: 20
  readiness:
    path: /modiaflatefs/internal/isReady
    initialDelay: 20
  prometheus:
    enabled: true
    path: /modiaflatefs/internal/metrics
  secureLogs:
    enabled: true
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 2000m
      memory: 512Mi
  ingresses:
    - https://app-{{ q_env }}.adeo.no/modiaflatefs
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 60
  azure:
    application:
      enabled: true
      tenant: trygdeetaten.no
      allowAllUsers: false
      claims:
        groups:
          - id: "67a06857-0028-4a90-bf4c-9c9a92c7d733" # 0000-GA-BD06_ModiaGenerellTilgang
  env:
    - name: APP_NAME
      value: "modiaflatefs"
    - name: APP_VERSION
      value: "{{ version }}"
    - name: MILJO_SUFFIX
      value: "-{{ q_env }}"
    - name: CSP_DIRECTIVES
      value: "default-src 'self';\
      script-src 'self' 'unsafe-inline';\
      font-src 'self' data:;\
      connect-src 'self' wss://veilederflatehendelser-{{ q_env }}.adeo.no sentry.gc.nav.no;\
      report-uri https://sentry.gc.nav.no/api/145/security/?sentry_key=b07212ac0fce4245b88145ad95706ce7&sentry_environment=preprod&sentry_release={{ version }};"
    - name: DISABLE_OPEN_AM
      value: "true"